### PR TITLE
footer updated

### PR DESCRIPTION
**Pull request by Yadvendra016**
footer is update
MyTODO - Personal - Microsoft​ Edge 03-10-2022 13_01_20
MyTODO - Personal - Microsoft​ Edge 03-10-2022 13_01_11

### CODE REVIEW

**Comment by Kirankp25** [comment]
all social media icons are not in their proper position

**Comment by Yadvendra016** [comment]
please merge it under hactoberfest then I will definitely fix it

**Comment by Kirankp25** [comment]
Your work is good, make it more efficient

**Comment by Yadvendra016** [comment]
done all set social icons are now under the contact info and also added some more content 
MyTODO - Personal - Microsoft​ Edge 03-10-2022 19_37_23

**Comment by Kirankp25** [comment]
> ### done all set social icons are now under the contact info and also added some more content
> MyTODO - Personal - Microsoft​ Edge 03-10-2022 19_37_23

Lgtm @Yadvendra016

**Pull request merged**
