### PR TITLE
Adding changes to Footer

### PR DESCRIPTION
**Pull request by aditi10701**

### CODE REVIEW

**Comment by Kirankp25** [comment]
SEND LIVE PR

**Comment by aditi10701** [comment]
> SEND LIVE PR or screenshot and star this repo

sent

**Comment by Kirankp25** [comment]
> 

...

**Comment by aditi10701** [comment]
how to send live pr?

**Comment by Kirankp25** [comment]
Take a screenshot and send here

**Comment by Kirankp25** [comment]
resolve merge conflicts

**Comment by aditi10701** [comment]
> Take a screenshot and send here

image

**Comment by aditi10701** [comment]
> resolve merge conflicts

How can I resolve the conflicts?

**Comment by Kirankp25** [comment]
go to the resolve option and remove unwanted code from your case base

**Comment by aditi10701** [comment]
conflicts resolved.

**Comment by Kirankp25** [comment]
> > Take a screenshot and send here
> 
> image

OUR UI is fully changed update your fork

**Comment by aditi10701** [comment]
How can I update my fork?

**Comment by Kirankp25** [comment]
> How can I update my fork?

go to synk fork option

**Comment by aditi10701** [comment]
Its showing everything on time, updated!
image

**Comment by Kirankp25** [comment]
now take review of updated UI

**Comment by aditi10701** [comment]
It shows the branch is already up to date

**Comment by aditi10701** [comment]
Why is this showing as not accepted in hacktoberfest?.

**Comment by Kirankp25** [comment]
> Why is this showing as not accepted in hacktoberfest?.

bcoz your Pr is not merged

**Comment by aditi10701** [comment]
what are the changes which needs to be done in order to merge the PR?

**Comment by Kirankp25** [comment]
take one screenshot and  send here ,i will tell you new issue ok

**Comment by aditi10701** [comment]
this one.
image

**Comment by Kirankp25** [comment]
> this one. image

NO

**Comment by Kirankp25** [comment]
Screenshot (317)

**Comment by aditi10701** [comment]
The footer looks different than the one I merged??

**Comment by Kirankp25** [comment]
> 

yes, There is no need to change the footer if you have any other issue  you can work on it

**Pull request closed without merging**
