### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by Mukkawar-Shlok**
image
image

### CODE REVIEW

**Comment by Kirankp25** [comment]
RESOLVE MERGE CONFLICTS

**Comment by Mukkawar-Shlok** [comment]
Resolved merge conflict

**Comment by Kirankp25** [comment]
ADD ONLY dark and white mode do not change the base UI

**Comment by Mukkawar-Shlok** [comment]
Can you conform orignal ui 
image
I will add dark mode based on this

**Comment by Kirankp25** [comment]
> Can you conform orignal ui image I will add dark mode based on this

Not this one

**Comment by Kirankp25** [comment]
Check current updated ui

**Comment by Mukkawar-Shlok** [comment]
This one?
image

**Comment by Kirankp25** [comment]
> This one? image

Yes

**Comment by Mukkawar-Shlok** [comment]
Should i keep it ?
image

**Comment by Kirankp25** [comment]
> Should i keep it ? image

Yeah sure

**Comment by Mukkawar-Shlok** [comment]
Please review
image

**Comment by Kirankp25** [comment]
Send both screen shots of dark and light mode

**Comment by Mukkawar-Shlok** [comment]
Light Mode (Normal)
image
Dark Mode
image

**Comment by Kirankp25** [comment]
Looks good to merge
ClappingLeonardoDicaprioGIF

**Comment by Mukkawar-Shlok** [comment]
Could you add accepted tag of  hacktoberfest ?

**Pull request merged**
