### PR TITLE
fixed text improved css

### PR DESCRIPTION
**Pull request by sanathan-git**
Improved overall css
Fixed issue add css #5 
Added changes about border, border-radius, box-shadow, colors. 

Thank you ✿

### CODE REVIEW

**Comment by Kirankp25** [comment]
Send screenshot of new updates

**Comment by sanathan-git** [comment]
Here is the screenshot after Updates

mytodo

**Comment by Kirankp25** [comment]
Take a full shot of a whole screen

**Comment by sanathan-git** [comment]
TODO

**Comment by Kirankp25** [comment]
Update your fork then work on it

**Pull request closed without merging**
