### PR TITLE
beta.csv

### PR DESCRIPTION
**Pull request by ctofficial**
hacktoberfest

### CODE REVIEW

**Comment by Kirankp25** [comment]
@ctofficial can you explain what changes you made here

**Comment by Kirankp25** [comment]
do not create such spam again
DontDoItDontYoudareGIF (2)

**Comment by ctofficial** [comment]
-_/ gawar spam to mat kar isse

**Comment by Kirankp25** [comment]
> -_/ gawar spam to mat kar isse

 what is this behavior...? If you really want to contribute, do some valid contribution not spam

**Comment by ctofficial** [comment]
huh how ironic. If you really want to consider it as spam do inform.  Why just made my repo as spam directly. Hence your behaviour shows that  you've got no manners at all ;/

**Comment by Kirankp25** [comment]
> @ctofficial can you explain what changes you made here

I already informed but no response from your side

**Pull request closed without merging**
