### PR TITLE
improved css

### PR DESCRIPTION
**Pull request by ShravaniAK**

### CODE REVIEW

**Comment by ShravaniAK** [comment]
earlier 
Screenshot 2022-10-02 at 10 56 42 AM


now
Screenshot 2022-10-02 at 10 57 21 AM

**Comment by Kirankp25** [comment]
can you reduce the size of the background  box of the edit

**Comment by Kirankp25** [comment]
Resolve merge conflicts

**Comment by Kirankp25** [comment]
this issue is alraedy updated...

**Pull request closed without merging**
