### PR TITLE
New Layout

### PR DESCRIPTION
**Pull request by shrey714**
Signed-off-by: Shrey <pshrey0000@gmail.com>

-New color theme
-New Designs
-Scrollbar designed

### CODE REVIEW

**Comment by Kirankp25** [comment]
take a screenshot of a new changes and send here

**Comment by shrey714** [comment]
Screenshot 2022-10-02 101718

**Comment by shrey714** [comment]
@Kirankp25 Also responsiveness is improved

**Comment by Kirankp25** [comment]
Looks good to merge
GoodJobNiceGIF

**Comment by Kirankp25** [comment]
star this repo

**Comment by shrey714** [comment]
yupp  ✨

**Pull request merged**
